### ISSUE TITLE
SROIE dataset issues.

### ISSUE THREAD

**Issue by Udit-git-acc** [ZeningLin/ViBERTgrid-PyTorch#14]
I am trying to reproduce the original paper results on the SROIE dataset and have some doubts regarding the same.
- Please share the your method on re-labeling the dataset with coordinates or your relabeled dataset.  
- Also please tell the input format of train and test labels ( file type, order). 
- In pipeline\sroie_data_preprocessing.py what are dir_test_root and dir_processed ? If I have to run code on my devise which one should I replace with the path of data in my device ?
Please help in these issues.

**Comment by ZeningLin** [comment]
**About dataset re-labeling:**
- We used an in-house labeling tool to re-label the data. First we generated the char-level OCR results (actually line-level with coordinates of each char) using an in-house OCR engine, then we marked the key-type category of each char comparing to the official SROIE gt labels.

**About data label input format:**
- Labes are in csv format. Each row should contain the left, top, right, bottom coordinates and the text string, key-type category of a word/text-line, see the example below
![image](https://user-images.githubusercontent.com/50203904/172849602-361031c9-ed07-4971-8411-a80467cb3e7d.png)

**About args in `pipeline/sroie_data_preprocessing.py`**
- `dir_test_root` refers to the root folder of the official raw SROIE test data, which should contain three folders: `img` with the images, `box` with the SROIE official OCR results, and `key` with the SROIE official key-type string labels. `dir_test_processed` is the dir to the processed label files.  

Here's my advice on arranging the dataset, if you want to use the sroie_data_preprocessing.py: 
1. Download the official SROIE dataset here(https://rrc.cvc.uab.es/?ch=13&com=downloads)
2. `0325updated.task1train(626p)` contains images and OCR results of the traing set, put the images in `img` folder and txt files in `box` folder. `txt` files in `0325updatd.task2train(626p)` are key-type labels, put them in the `key` folder. The arg `dir_train_root` is the dir to the root of the three folders mentioned above. The arg `dir_train_processed` is the dir to the processed csv labels generated by the `sroie_data_preprocessing.py`, named `label`. Put the `img`, `key` and `label` folders in the same root named `train`.
3. Download the raw data of test set from the link provided at the bottom of the official page, (https://rrc.cvc.uab.es/?com=downloads&action=download&ch=13&f=aHR0cHM6Ly9ycmMuY3ZjLnVhYi5lcy9kb3dubG9hZHMvU1JPSUVfdGVzdF9ndF90YXNrXzMuemlw and https://rrc.cvc.uab.es/?com=downloads&action=download&ch=13&f=aHR0cHM6Ly9ycmMuY3ZjLnVhYi5lcy9kb3dubG9hZHMvU1JPSUVfdGVzdF9pbWFnZXNfdGFza18zLnppcA==). Follow the instructions in `2`, but name the folder as `test`. Put it in the same root with `train` folder and named the root as `SROIE`. 
4. Change the arg `data_root` in the config yaml file to the `SROIE` folder, then the dataloader can recognize the the data and load them automatically when calling train scripts.

**Comment by Udit-git-acc** [comment]
Thanks for the earlier reply just a few more concerns I have, 

- The txt file in box folder should be converted to csv format with format as you showed in the snippet ?

Thanks for the reply and help.

**Comment by ZeningLin** [comment]
> 

No, just keep it as the txt format. (See line 147 in sroie_data_preprocessing.py, I used a `readline()` rather than `pandas.read_csv()`). The csv format showed in the snippet is the required format of the processed labels.

**Comment by Udit-git-acc** [comment]
Thanks for the reply, since you mentioned that we can use .txt file. I think there is some error 

- line 109, sroie_data_preprocessing.py : You have mentioned directory to bbox csv file I think that should be directory to bbox txt file.
- After defining the directory we are calling data_parser function, in which we are calling data_preprocessing_pipeline function which is expecting bounding box in csv file and key in json format (line 316 and 318 respectfully)

That why when I am running it with .txt files in bbox folder I am getting an error that "FileNotFoundError: [Errno 2] No such file or directory"

**Comment by ZeningLin** [comment]
Hello,

Sorry for the mistake, since the sroie_data_preprocessing.py was written a long time ago and I’ve forgotten some of the details. Try converting the .txt files to .csv format by changing the suffix and see whether it works or not, or just change the `file.replace(“.json”, “.csv”)` to `file.replace(“.json”, “.txt”)` in line 335.

This script was written during my learning phase last year, and it certainly do need an update. Using pandas as the bbox file parser is much more feasible. I will update the code if I were free.

Best regards,
Zening Lin

**Comment by Udit-git-acc** [comment]
<3<3
