### ISSUE TITLE
Validation in CRF mode

### ISSUE THREAD

**Issue by furkanpala** [ZeningLin/ViBERTgrid-PyTorch#18]
Hi, thanks for your effort.

I noticed a problem in the `pipeline.train_val_utils.validate` when we are running on `crf` classifier mode such that the `inference` function the `crf.py` returns the predicted target sequence (which is actually predicted class ids), not the probabilities for each class. Then, `pipeline.train_val_utils.validate` function, we are getting the predicted class ids by running `torch.argmax`. However, as I said, we do not have the probailities here, instead we directly have the predicted class ids.

I think we can solve this by adding a `is_crf` argument in the `pipeline.train_val_utils.validate` function and an if block decides to apply the argmax or not.

Also, irrelevant but there is a type here https://github.com/ZeningLin/ViBERTgrid-PyTorch/blob/97af7690be834b57c072fd3a872dcbc62b472461/model/field_type_classification_head.py#L474

Thanks, sincerely.

**Comment by ZeningLin** [comment]
Hi~

When using the crf decoder, the seqeval library will be used as the evaluation metric, in this case only the predicted class is needed. Maybe a restriction should be added in the validation step. I will work on it later~

**Comment by furkanpala** [comment]
Thanks...
